# Generated by Django 3.0.5 on 2020-04-12 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_detail',
            old_name='uname',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='user_detail',
            name='birth_date',
        ),
    ]
