# Generated by Django 3.0.5 on 2020-04-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0002_auto_20200412_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_detail',
            name='user_name',
        ),
        migrations.AddField(
            model_name='user_detail',
            name='email',
            field=models.EmailField(default='none', max_length=20),
        ),
    ]
