# Generated by Django 3.0.5 on 2020-04-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0003_auto_20200412_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='email',
            field=models.EmailField(max_length=20),
        ),
    ]
