# Generated by Django 3.0.5 on 2020-04-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0004_auto_20200412_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=6),
        ),
    ]
